### ISSUE TITLE
Spring boot maven based Rivr sample

### ISSUE THREAD

**Issue by D41138761** [nuecho/rivr#10]
we are trying to build application to generate voicexml using Spring Boot, looks like sample rivr-cookbook is not working or not loading the dialogue class. Can you please share sample spring boot - maven based project ?

**Comment by gawi** [comment]
What have you tried so far? Can you share it here? Also, can you be more specific when you say that the dialogue class is not loading?

I've done multiple projects using Spring Boot. I'm mostly using Gradle and not Maven though.

**Comment by D41138761** [comment]
we made it work in Spring boot maven, thanks

**Comment by gawi** [comment]
Great!
