### ISSUE TITLE
Invoking API with Rivr

### ISSUE THREAD

**Issue by D41138761** [nuecho/rivr#11]
Is there any way to call API (REST) and validate user provided input using Rivr?

**Comment by gawi** [comment]
Rivr has no knowledge of APIs whatsoever. You have to provide the API client and invoke it from your Java code with the input provided by the user. 

Rivr is all about centralising everything on the Java server side. Thus, you should do the integration of the API from the Java code.

**Comment by D41138761** [comment]
Thanks for the response. 
we want to construct **data tag** as below which is calling any URL. Looks like we dont have any class in rivr to construct it directly . 
<data name="return_data" srcexpr="some_url" method="post" namelist="var1 var2 var3" />

**Comment by gawi** [comment]
Once again, you shouldn't use the `<data>` element to do API calls. Instead, you should prefer make the call from the Java code, which allows you to do many things not possible with the `<data>` element:
- handle timeout
- add HTTP headers (for authentication, for instance)
- use a method different from `POST`or `GET` (which are the only 2 values allowed by the VoiceXML 2.1 recommendation).

**Comment by D41138761** [comment]
I am confused. my understanding is data tag is part of vxml ,  system which is executing vxml and the data tag will call the api directly and get response ? or how can vxml call our java code to make api call ? , any sample code we can refer?

**Comment by gawi** [comment]
Yes, you are right when you say that `<data>` is part of VoiceXML 2.1.  However, it has not been exposed in Rivr because there is a much better way to do it on the server side.

With Rivr, when you do an application, you do not generate a large VoiceXML document.  Instead, Rivr generates a series of small VoiceXML document *and posts the result of the document execution back to the server* every time.

Here's a very basic code sample.  I'm using `HttpURLConnection` but you should really use something better (there are many options when it comes to API clients in Java):

```java
package com.nuecho.rivr.cookbook.dialogue;

import java.io.*;
import java.net.*;
import java.nio.charset.*;

import javax.json.*;

import com.nuecho.rivr.core.channel.*;
import com.nuecho.rivr.core.dialogue.*;
import com.nuecho.rivr.core.util.*;
import com.nuecho.rivr.voicexml.dialogue.*;
import com.nuecho.rivr.voicexml.turn.first.*;
import com.nuecho.rivr.voicexml.turn.input.*;
import com.nuecho.rivr.voicexml.turn.last.*;
import com.nuecho.rivr.voicexml.turn.output.*;
import com.nuecho.rivr.voicexml.turn.output.audio.*;
import com.nuecho.rivr.voicexml.turn.output.grammar.*;

public class Menu implements VoiceXmlDialogue {

    @Override
    public VoiceXmlLastTurn run(VoiceXmlFirstTurn firstTurn, VoiceXmlDialogueContext context) throws Timeout,
            InterruptedException {

        String number = getNumber(context);

        try {
            String processedNumber = invokeApi(number);
            Message resultMessage = new Message("resultMessage",
                                                new SpeechSynthesis("The result is: " + processedNumber));
            DialogueUtils.doTurn(resultMessage, context);
        } catch (IOException exception) {
            Message errorMessage = new Message("errorMessage",
                                               new SpeechSynthesis("An error occured: "
                                                                   + exception.getMessage()));
            DialogueUtils.doTurn(errorMessage, context);
        }

        return new Exit("exit");
    }

    private String getNumber(VoiceXmlDialogueContext context) throws Timeout, InterruptedException {
        String number = null;

        do {
            DtmfRecognition dtmfRecognition = new DtmfRecognition(new GrammarReference("builtin:dtmf/digits"));
            SpeechSynthesis promptText = new SpeechSynthesis("Enter a number.");

            Interaction interaction = OutputTurns.interaction("askNumber")
                                                 .addPrompt(dtmfRecognition, promptText)
                                                 .build(dtmfRecognition, Duration.milliseconds(5));

            VoiceXmlInputTurn inputTurn = DialogueUtils.doTurn(interaction, context);

            if (inputTurn.getRecognitionInfo() != null) {
                JsonArray recognitionResult = inputTurn.getRecognitionInfo().getRecognitionResult();
                number = recognitionResult.getJsonObject(0).getString("interpretation");
            }
        } while (number != null); //loop until valid value is provided

        return number;
    }

    public static String invokeApi(String number) throws IOException {
        URL apiUrl = new URL("http://localhost:8080/api/x/v1/numbers/" + number);
        HttpURLConnection connection = (HttpURLConnection) apiUrl.openConnection();
        connection.setRequestMethod("GET");

        int responseCode = connection.getResponseCode();
        if (responseCode != 200) throw new IOException("Non-200 reponse from API: " + responseCode);

        return readAllStream(connection.getInputStream());
    }

    public static String readAllStream(InputStream inputStream) throws IOException {
        int bufferSize = 1024;
        char[] buffer = new char[bufferSize];
        StringBuilder out = new StringBuilder();
        Reader in = new InputStreamReader(inputStream, StandardCharsets.UTF_8);
        for (int numRead; (numRead = in.read(buffer, 0, buffer.length)) > 0;) {
            out.append(buffer, 0, numRead);
        }
        return out.toString();
    }
}
```
This will generate a first document where user will be prompted for a number. Once the number is provided, the result will be sent back to Rivr and the Dialogue will continue where we left off (in the `doTurn` method). Then the call to the API can be done in the Java code. Following that, we  create another VoiceXML document that reads the result back to the user. Then we terminate the dialogue (with an `<exit>` element).

**Comment by D41138761** [comment]
Thanks, this helps to understand the rivr better. 

what is the equivalent vxml to this , to run the vxml from any system ?
