### ISSUE TITLE
Can we generate our own voiceXml forms by passing parametes like string using voicexmloutputTurn or VoiceXmlDialogue ? Is there any other method?like VoiceXmlLastTurn run(VoiceXmlFirstTurn,VoiceXmlDialogueContext, String)

### ISSUE THREAD

**Issue by Rohith2304** [nuecho/rivr#14]

**Comment by gawi** [comment]
@Rohith2304, (You are using the issue section of Rivr to ask questions. I'm ok to answer those questions but please, do not put the while question in the subject field.)

Also, you keep asking about custom VoiceXML generation, which suggests that you are thinking about Rivr being a static VoiceXML application generator, which Rivr is not. Rivr delivers VoiceXML documents dynamically at run-time. Rivr is feeding VoiceXML document directly to the VoiceXML platform. Please confirm that you understand that and explain why you need to customize the VoiceXML generated by Rivr.

**Comment by Rohith2304** [comment]
Sorry, I shouldn't have put while question in the subject field. Now I understood the concept after your explanation.
Thanks for your response
