### ISSUE TITLE
how to get dialogue response  content-type as application/xml instead of application/voicexml+xml ?

### ISSUE THREAD

**Issue by D41138761** [nuecho/rivr#16]
How to get dialogue response  content-type as `application/xml` instead of `application/voicexml+xml`?

**Comment by gawi** [comment]
The standard content type is `application/voicexml+xml`as per [RFC 4267](https://www.ietf.org/rfc/rfc4267.txt) and there is no mechanism within Rivr that you can use to change the content type. 

You can however implement a servlet filter to change the content-type.

**Comment by D41138761** [comment]
ok thanks
