### ISSUE TITLE
Avaya Experience Portal tack_trace":"c.n.r.c.s.s.SessionNotFoundException: Unable to find session [error]

### ISSUE THREAD

**Issue by nmvprasad** [nuecho/rivr#18]
Avaya Experience Portal [tack_trace":"c.n.r.c.s.s.SessionNotFoundException:]
[RivrErrorLog.txt](https://github.com/nuecho/rivr/files/7125469/RivrErrorLog.txt)
{"ts":"2021-09-08T02:39:45.755Z","logLevel":"ERROR","logMessage":"Servlet.service() for servlet [voiceXmlDialogueServlet] threw exception","logThreadId":"http-nio-8090-exec-3","logClass":"o.a.juli.logging.DirectJDKLog","logMethod":"log","env":{"hostname":"8c30a61321d8","containerName":"containerName_IS_UNDEFINED","containerNamespace":"containerNamespace_IS_UNDEFINED"},"application":{"name":"appName_IS_UNDEFINED","version":"appVersion_IS_UNDEFINED"},"stack_trace":"c.n.r.c.s.s.SessionNotFoundException: Unable to find session [error]\n\tat c.n.r.c.s.DialogueServlet.getExistingSession(DialogueServlet.java:537)\n\tat c.n.r.c.s.DialogueServlet.getSession(DialogueServlet.java:520)\n\tat c.n.r.c.s.DialogueServlet.process(DialogueServlet.java:401)\n\tat c.n.r.c.s.DialogueServlet.doGet(DialogueServlet.java:270)\n\tat c.n.r.v.s.VoiceXmlDialogueServlet.doGet(VoiceXmlDialogueServlet.java:145)\n\tat j.s.http.HttpServlet.service(HttpServlet.java:626)\n\tat j.s.http.HttpServlet.service(HttpServlet.java:733)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat o.s.c.s.i.w.s.TracingFilter.doFilter(TracingFilter.java:68)\n\tat o.s.c.s.a.i.w.LazyTracingFilter.doFilter(TraceWebServletConfiguration.java:121)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat o.a.c.c.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710)\n\tat o.a.c.c.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)\n\tat o.a.c.c.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)\n\tat o.a.c.c.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)\n\tat o.a.c.c.StandardHostValve.custom(StandardHostValve.java:398)\n\tat o.a.c.c.StandardHostValve.status(StandardHostValve.java:257)\n\tat o.a.c.c.StandardHostValve.invoke(StandardHostValve.java:179)\n\tat o.a.c.v.ErrorReportValve.invoke(ErrorReportValve.java:92)\n\tat o.a.c.c.StandardEngineValve.invoke(StandardEngineValve.java:78)\n\tat o.a.c.c.CoyoteAdapter.service(CoyoteAdapter.java:346)\n\tat o.a.c.h.Http11Processor.service(Http11Processor.java:374)\n\tat o.a.c.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\n\tat o.a.c.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)\n\tat o.a.t.u.n.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)\n\tat o.a.t.u.n.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat o.a.t.u.t.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:829)\n"},

**Comment by gawi** [comment]
For some reason, AEP tried to access some URI http://your_server:8080/your_context/your_dialogue/**error**
When invoking a dialogue, you are not allowed to pass anything in the path info as it is used to pass the session ID. Here, you are passing `error` in the path info (hence Rivr is complaining that the session "error" does not exist). Not sure why this is happening. You probably have some sort of error handling document somewhere pointing back to this URI.

Suppose your dialogue servlet (i.e. `VoiceXmlDialogueServlet`) is mapped to the `https://myServer:8080/context/myDialogue/*` URI. You must instruct AEP to use `https://myServer:8080/context/myDialogue` as the URI for the speech application. Note that we are not passing anything in the path info, i.e. there's nothing following `myDialogue`.

Rivr will then generate VoiceXML documents that will point back to itself by creating URI having the session ID embedded in it.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<vxml application="/rivr-test/dialogue/root/ae8cb3f2-610e-4531-bf7b-076be7f6b26d" version="2.1" xmlns="http://www.w3.org/2001/vxml">
    <!--  NOTE: Rivr output simplified for clarity -->

    <form id="form">
        <block>
            <prompt>Some message here...</prompt>
            <goto next="#submitForm"/>
        </block>
    </form>

    <form id="submitForm">
        <block>
            <var expr="application.rivr.toJson(application.rivr.inputTurn)" name="inputTurn"/>
            <submit method="post" namelist="inputTurn" next="/rivr-test/dialogue/ae8cb3f2-610e-4531-bf7b-076be7f6b26d/0/welcome-message"/>
        </block>
    </form>
</vxml>
```

In the exemple above, the "submit back" URI is `/rivr-test/dialogue/ae8cb3f2-610e-4531-bf7b-076be7f6b26d/0/welcome-message` where `ae8cb3f2-610e-4531-bf7b-076be7f6b26d` is the session ID, `0` is the turn index  and `welcome-message` is the turn name.

**Comment by nmvprasad** [comment]
Thank you this issue resolved now after fixing audio file name in prompt
