### ISSUE TITLE
how to write java code for return namelist in subdialogue

### ISSUE THREAD

**Issue by D41138761** [nuecho/rivr#24]
we need to return using namelist for a subdialouge in vxml
< return namelist="test test2 test3" />

java - using Return object as below 
return new Return("namelist", returnValues);
or 
return new Return("return", returnValues);

is the above code correct to send returnValues as namelist?

**Comment by gawi** [comment]
The first parameter of the `Return` constructor is just a name. Use whatever you want. What's important is to pass the `VariableList` object.

**Comment by D41138761** [comment]
thanks
