### ISSUE TITLE
Speech and DTMF recognition together

### ISSUE THREAD

**Issue by D41138761** [nuecho/rivr#26]
We have requirement to ask user to provide zipcode by playing audio "**Please say or enter the zip code of your service address**."  User can either say or type zipcode. Is there any way common recognition logic to receive user input instead of using Speech and DTMF recognition separately or one after another ?

**Comment by gawi** [comment]
For `Interaction.Builder.build()` and `Interaction.Builder.addPrompt()` methods, there are some signatures accepting both  `DtmfRecognition` and `SpeechRecognition` objects.

**Comment by D41138761** [comment]
thanks. it worked
