### ISSUE TITLE
Missing namespace attribute in the root vxml node.

### ISSUE THREAD

**Issue by sjacek** [nuecho/rivr#3]
In the debug log from rivr-voicexml we see
`Content: <?xml version="1.0" encoding="UTF-8"?><vxml application="/rivr-prompt/root/85cef493-45bf-44d1-9d3f-a312643fd71a" version="2.1" xml:lang="en-US">`
The root node is missing namespace attribute.

The broken vxml goes from dialogues to a VXML browser.  It causes faults on IBM Websphere Voice Server.

**Comment by gawi** [comment]
What Java run-time are you using (vendor, version)? I've tested with many different versions (Oracle 6, 7, OpenJDK 8) and I see the `xmlns` attribute without having to use the proposed fix.

It may have to do with the specific implementation of the DOM API used by that runtime.  I agree that using the proper namespace-related methods of the DOM API is more correct. I'll look into it and assess impact on different Java run-time versions.

**Comment by sjacek** [comment]
I use Oracle JDK 6 and IBM JDK 6 on Windows, Linux and AIX.  The effect is the same on every platform.
