### ISSUE TITLE
Unit Testing in VoiceXML

### ISSUE THREAD

**Issue by Tritrita** [nuecho/rivr#6]
Hi ,

May I know how is Unit testing performed over after building an VoiceXML Application.

It is given that ,its capable of doing unit testing,but I dont undestand where and how it is done.?
 
Thanks,

**Comment by pdeschen** [comment]
@tritrita

You may have a look at the cookbook’s about unit testing

https://github.com/nuecho/rivr-cookbook/wiki/Simple-dialogue-tests
