### ISSUE TITLE
mavenCentral is not supported in Gradle 5.3 or latest

### ISSUE THREAD

**Issue by sgana123** [nuecho/rivr#9]
Hi - mavenCentral pom tags are not recognized in Gradle latest version.
Could you please guide on How to substitute with?
maven { 
			url = "http://repo.maven.apache.org/maven2"			
		}

--------------
Files:
rivr-master\build-instructions.md
rivr-master\build.gradle
rivr-master\rivr-voicexml-dialogue-runner\build.gradle

repositories { mavenCentral() }
repositories {
            mavenCentral{
                pom.project{ packaging 'jar' }
            }
        }
repositories {
        mavenCentral {
            pom.project { packaging 'war' }
        }
    }

mavenDeployer(name: 'mavenCentral')

**Comment by gawi** [comment]
Confirmed using Gradle 5.3.

We are using an archaic technique to produce and publish the maven artefacts. I will use the `maven-publish`Gradle plugin to fix those issues.

In the mean time, I recommend using the Gradle wrapper provided with the source.

**Comment by gawi** [comment]
I have fixed the problem and kept the 'maven' plugin. This is now published to master and 1.0-fix.  Gradle wrapper is configured to use Gradle 5.3.
